export declare const getSetValuesExamples: () => void;
export declare const autoBindingValuesExamples: () => void;
export declare const autoGeneratedLabelsExamples: () => void;
export declare const minMaxExamples: () => void;
//# sourceMappingURL=examples.d.ts.map