export declare const getSetValuesExamples: () => void;
export declare const autoBindingValuesExamples: () => void;
export declare const autoGeneratedLabelsExamples: () => void;
export declare const minMaxExamples: () => void;
export declare const roundExamples: () => void;
export declare const stepExamples: () => void;
export declare const nonLinearStepExamples: () => void;
//# sourceMappingURL=examples.d.ts.map