import '../../../../dist/plugins/tcrs-themes.min.css';
import '../../../../dist/plugins/tcrs-pointer-shapes.min.css';
import '../../../../dist/plugins/tcrs-binding-labels.min.js';
import '../../../../dist/plugins/tcrs-generated-labels.min.js';
import '../../../../dist/plugins/tcrs-storage.min.js';
import '../../../../dist/plugins/tcrs-moving-tooltip.min.js';
import '../../../../dist/plugins/tcrs-origin-center.min.js';
import '../../../../dist/plugins/tcrs-marks.min.js';
import '../../../../dist/toolcool-range-slider.min.js';

import {
  getSetValuesExamples,
  autoBindingValuesExamples,
  autoGeneratedLabelsExamples,
  minMaxExamples,
  roundExamples,
  stepExamples,
  nonLinearStepExamples,
  dataExamples,
  withHeightBorderRadiusExamples,
  colorExamples,
  themesExamples,
  pointerShapesExamples,
  animationShapesExamples,
  verticalExamples,
  rightToLeftExamples,
  disabledExamples,
  rangeDraggingExamples,
  pointersOverlapExamples,
  softLimitsExamples, createdSliderDynamicallyExamples, movingTooltipExamples, marksPluginExamples
} from './examples';

const initMobileMenu = () => {
  const $btn = document.getElementById('mobile-menu-btn');
  if(!$btn) return;

  $btn.addEventListener('click', (evt) => {
    evt.stopPropagation();
    document.body.classList.toggle('mobile-menu-opened');
  });

  document.body.addEventListener('click', () => {
    document.body.classList.remove('mobile-menu-opened');
  });

  const $sideMenu = document.getElementById('side-menu');
  if(!$sideMenu) return;

  $sideMenu.addEventListener('click', (evt) => {
    evt.stopPropagation();
  });

  const $close = document.getElementById('mobile-menu-close-btn');
  if(!$close) return;

  $close.addEventListener('click', () => {
    document.body.classList.remove('mobile-menu-opened');
  });
};

const initMenuScroll = () => {
  const $menu = document.querySelector('.side-menu');
  if(!$menu) return;

  const path = window.location.pathname;
  const $link = $menu.querySelector(`a[href='${ path }']`);
  if(!$link) return;

  $link.scrollIntoView({
    block: 'center',
  });
};

const init = () => {
  initMobileMenu();
  initMenuScroll();

  getSetValuesExamples();
  autoBindingValuesExamples();
  autoGeneratedLabelsExamples();
  minMaxExamples();
  roundExamples();
  stepExamples();
  nonLinearStepExamples();
  dataExamples();
  withHeightBorderRadiusExamples();
  colorExamples();
  themesExamples();
  pointerShapesExamples();
  animationShapesExamples();
  verticalExamples();
  rightToLeftExamples();
  disabledExamples();
  rangeDraggingExamples();
  pointersOverlapExamples();
  softLimitsExamples();
  createdSliderDynamicallyExamples();
  movingTooltipExamples();
  marksPluginExamples();
};

document.addEventListener('DOMContentLoaded', () => {
  init();
});

export {};
