# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  workflow_dispatch: # Putting here is also fine!!
  schedule:
  - cron: '32 2 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue/PR has been automatically marked as stale because it has not had any update for 7 days. It will be closed automatically if no further update occurs in 7 day.'
        stale-pr-message: 'This issue/PR has been automatically marked as stale because it has not had any update for 7 days. It will be closed automatically if no further update occurs in 7 day.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        days-before-issue-stale: 7
        days-before-issue-close: 3
